### ISSUE TITLE
How do you handle map.on('load')?

### ISSUE THREAD

**Issue by chriswhong** [kturney/ember-mapbox-gl#15] opened 2017-08-09 21:09 UTC
I tried: 

```
{{#mapbox-gl id='lu-map' initOptions=initOptions as |map|}}
  {{map.on 'load' (action 'handleLoad')}}
{{/mapbox-gl}}
```
but my handleLoad action never fires...  

What I really want to do is disable `scrollZoom`, but I am not sure where to do it.  Thanks!

**Comment by allthesignals** [comment] 2017-08-10 01:37
Duplicate of #5 - I forgot I already opened an issue for this, was asked and answered. Oops!

**Comment by kturney** [comment] 2017-08-14 00:41
@chriswhong you should be able to pass `scrollZoom: false` in `initOptions`.

I agree the `load` event not firing is not intuitive behavior.
The reason `load` doesn't fire is because the `mapbox-gl` component waits for the load event to yield, so `map.on 'load'` is bound after the load event on the map has already fired. The `mapbox-gl` component does however provide a `mapLoaded` hook that will be called when the load event is received.

Sorry for taking so long to respond.
I totally missed that a new issue was created.

**Closed as completed** 2017-08-21 19:13 UTC
